name: Build release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: '1.0.0'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            rid: linux-x64
            artifact_name: matrix-linux
          - os: windows-latest
            rid: win-x64
            artifact_name: matrix-windows.exe
          - os: macos-latest
            rid: osx-arm64
            artifact_name: matrix-macos-arm
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Publish
      run: |
        dotnet publish -c Release -o publish -r ${{ matrix.rid }} /p:PublishSingleFile=true /p:PublishTrimmed=true
        mv publish/matrix${{ matrix.os == 'windows-latest' && '.exe' || '' }} ${{ matrix.artifact_name }}

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.artifact_name }}
        path: ${{ matrix.artifact_name }}

  create-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        path: artifacts
    
    - name: Display structure of downloaded files
      run: ls -R artifacts
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.event.inputs.version }}
        name: Release ${{ github.event.inputs.version }}
        files: |
          artifacts/matrix-linux/matrix-linux
          artifacts/matrix-windows.exe/matrix-windows.exe
          artifacts/matrix-macos-arm/matrix-macos-arm
        draft: false
        prerelease: false