name: Build release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    #- name: Test
    #  run: dotnet test --no-restore --verbosity normal
      
    - name: Publish
      run: dotnet publish -c Release -o publish -r ${{ matrix.os == 'ubuntu-latest' && 'linux-x64' || matrix.os == 'windows-latest' && 'win-x64' || 'osx-x64' }} --self-contained

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: matrix-${{ matrix.os }}
        path: publish

  create-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          matrix-ubuntu-latest/*
          matrix-windows-latest/*
          matrix-macos-latest/*
